import { LogoComponent } from "@/components/LogoBar";
import { SideBar } from "@/components/data-visualizer/Sidebar";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Exante Data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-screen overflow-hidden">
      <div className="hidden lg:block lg:h-[7vh] min-h-10">
        <LogoComponent />
      </div>
      <div className="flex flex-col lg:flex-row bg-slate-100 lg:h-[94vh] max-lg:h-screen">
        <SideBar /> 
        <div
          className="grow p-4 overflow-x-hidden overflow-y-scroll max-lg:h-[94vh]"
          // style={{ maxHeight: "94vh" }}
        >
          {children}
        </div>
      </div>
    </div>
  );
}
