name: Build and publish chart-generator-exante-data to DOOC

on:
  #push:
  #  branches: [devops]
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build_and_push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
      - name: update env
        run: |
          touch $GITHUB_WORKSPACE/.env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL_PROD }}" >> $GITHUB_WORKSPACE/.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL_PROD}}" >> $GITHUB_WORKSPACE/.env
      - name: Build image 
        run: docker build -t chart-generator-exante-data -f Dockerfile .
      - name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DO_TOKEN}}
      - name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
      - name: Tag image 
        run:
          docker tag chart-generator-exante-data registry.digitalocean.com/exante-data/chart-generator-exante-data
      - name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/exante-data/chart-generator-exante-data